### PR TITLE
Update tap version

### PR DESCRIPTION
**Pull request by bzoz**
This makes tests pass on Windows. Currently it is broken because of https://github.com/tapjs/node-tap/issues/373

### CODE REVIEW

**Comment by jdalton** [comment]
@isaacs This PR would also allow unskipping Windows tests for `semver` in Node's CitGM.

**Comment by jdalton** [comment]
Thank you @isaacs!

Would it be helpful if I pop-in to similar issues for other packages you maintain and identify them as related to CitGM? _(this is related to an MS effort to improve Node on Windows)_

**Comment by isaacs** [comment]
Thanks!  I actually bumped it all the way to 12.0.1, but effect should be the same.  Do you need a push to npm as well, or does citgm pull from the git repo?

**Comment by isaacs** [comment]
@jdalton Yes, please, if there's anything I or npm can do to help make node on windows better, definitely feel free to ping me.  Making citgm better is always winful.

**Comment by jdalton** [comment]
@isaacs

> Do you need a push to npm as well, or does citgm pull from the git repo?

Yes. CitGM references the latest version number published to npm and maps it back to a GitHub tag in the package's repo to get its tarball for testing.

> Yes, please, if there's anything I or npm can do to help make node on windows better, definitely feel free to ping me. Making citgm better is always winful.

Thank you, will do!

**Pull request closed without merging**
