### PR TITLE
fix: better handling of whitespace

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Review by wraithgar — APPROVED** [review]

**Comment by SymbioticKilla** [comment]
@lukekarrys @wraithgar 
It would be awesome to have this fix in 5.x and 6.x branches
Thank you!

**Comment by wraithgar** [comment]
At this time, seeing as how v5/6 is a single 1400+ line file with outdated testing deps and no working CI we do not have plans to backport this.

**Comment by joaomoreno** [comment]
@wraithgar, while I totally side with you on this, it's much more difficult to bulk upgrade semver to v7 across deep dependency trees of even medium side projects. We have 10+ usages of it just in [microsoft/vscode](https://github.com/microsoft/vscode). This is a compliment: semver is very popular and its usage is widespread. We thank you for this library! ❤️ 

That being said, we like to put our commits where our mouth is. I've backported the fix to v5: https://github.com/npm/node-semver/compare/v5.7.1...joaomoreno:joao/backport-564-to-v5?expand=1. I've also fixed the test suites and added the relevant test cases, all green: https://asciinema.org/a/593286. I hope you can consider this for releasing an eventual 5.7.2 version, given your review. If successful, I would gladly backport the same fix to v6.

I can't quite create a PR, since there's no v5 branch to upstream against. If you'd like to roll this forward, let's create a v5 branch and we'll create a PR from my ref.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
The babel team has also stated that they'd fork v6 to fix the issue. https://github.com/babel/babel/issues/15720#issuecomment-1608382204

**Comment by nicolo-ribaudo** [comment]
Babel maintainer here — I pubished a fork of v6 with this fix backported at https://www.npmjs.com/package/@nicolo-ribaudo/semver-v6, because we cannot upgrade to v7.

**Comment by simnalamburt** [comment]
To override semver v6 with forked version with yarn:
```bash
yarn set resolution semver@npm:^6.0.0 npm:@nicolo-ribaudo/semver-v6@^6
```

**Comment by lukekarrys** [comment]
I created release branches for [`release/v5`](https://github.com/npm/node-semver/tree/release/v5) and [`release/v6`](https://github.com/npm/node-semver/tree/release/v6). They will be ready to land commits fixing the CVE in both release lines once the next version of `@npmcli/template-oss` is released (ref: https://github.com/npm/template-oss/pull/326).

Once PRs are made to either of those branches, when they land they will follow our current automated release process. I will update this issue again once those are ready.

@joaomoreno @nicolo-ribaudo If you would be willing to PR your fixes to those branches once they are ready it would be greatly appreciated! 🙌🏼

**Comment by joaomoreno** [comment]
This is great, we really appreciate the effort! ❤️ 

Here's my PR for v5: https://github.com/npm/node-semver/pull/585

**Comment by nicolo-ribaudo** [comment]
I will open a PR later for v6, thank you!

**Comment by lukekarrys** [comment]
@nicolo-ribaudo the `release/v6` branch is ready. I made a list of all the commits on `main` that should be backported here: https://github.com/npm/node-semver/pull/585#issuecomment-1625868681.

If you'd like to try to get all of them in your PR go for it 😄 Otherwise just the fix your have in your fork would be great!

**Comment by simnalamburt** [comment]
I appreciate all of your efforts to backport patches to versions that are over 3 years old.

**Pull request merged**
