### PR TITLE
Clarify Caret Ranges

### PR DESCRIPTION
**Pull request by lm1**

### CODE REVIEW

**Comment by joeledwards** [comment]
I think the term `value` is clearer than `item`. All for replacing `digit`.

**Comment by lm1** [comment]
I thought 'tuple value' could be a bit ambiguous, but it should be clear it's not referring to entire tuple in this context.

**Comment by joeledwards** [comment]
Perhaps 'element'?

**Comment by isaacs** [comment]
e09ecf8 thanks!

**Pull request closed without merging**
