### PR TITLE
fix: better handling of whitespace (backport to v5)

### PR DESCRIPTION
**Pull request by joaomoreno**
This backports the security fix https://github.com/npm/node-semver/pull/564 to v5.

### CODE REVIEW

**Comment by wraithgar** [comment]
https://github.com/npm/node-semver/issues/580 should be fixed before we go backporting anything so we don't bring new bugs along.

**Comment by wraithgar** [comment]
https://github.com/npm/node-semver/issues/587 Also needs to be fixed

**Comment by lukekarrys** [comment]
the latest template-oss changes have been applied to `release/v5`. @joaomoreno can you rebase your branch so it only includes the `semver.js` and `test/` changes?

**Comment by lukekarrys** [comment]
The full set of changes that should be backported are:
- https://github.com/npm/node-semver/commit/717534ee353682f3bcf33e60a8af4292626d4441
- https://github.com/npm/node-semver/commit/abdd93d55496d22e3c15a454a5cf13f101e48bce
- https://github.com/npm/node-semver/commit/cc6fde2d34b95cb600d126649d926901bd2a9703
- https://github.com/npm/node-semver/commit/99d8287516a1d2abf0286033e2e26eca6b69c09f

**Comment by lukekarrys** [comment]
@joaomoreno i was able to push to your branch with the relevant commits. waiting on CI to see if tests pass in older versions of node

**Comment by joaomoreno** [comment]
Sounds good, thanks @lukekarrys!

**Review by wraithgar — APPROVED** [review]

**Comment by G-Rath** [comment]
I've opened https://github.com/github/advisory-database/pull/2483 updating the advisory for v5

**Comment by G-Rath** [comment]
and I've opened https://github.com/github/advisory-database/pull/2484 updating the advisory again for v6 and v5.

**Comment by lukekarrys** [comment]
Thanks @G-Rath!

**Comment by joaomoreno** [comment]
Thanks all!

**Pull request merged**
