### PR TITLE
Add leading zeros remove

### PR DESCRIPTION
**Pull request by lomby92**
Coerce method can remove leading zeros from minor, major and patch.
EG: '0.004.02' -> '0.4.2'

### CODE REVIEW

**Comment by lomby92** [comment]
Ok @bartvanandel , i will edit as you suggested

**Comment by erichs** [comment]
@isaacs this is still an active issue. Can this conflict be resolved and the patch applied?

**Comment by lomby92** [comment]
@isaacs 
I can update the PR, let me know if this feature could be useful

**Comment by yedlosh** [comment]
@bartvanandel Could this be merged in to finally fix #232?

**Comment by bartvanandel** [comment]
I don't think I can merge this, I don't own this repo.

**Comment by Vlad-AndreiMunteanu** [comment]
Is this going to get merged at all? I face the same issue with leading zeros today.

**Comment by lukekarrys** [comment]
This can be done by using `loose: true` currently, but it can't be made the default in order to be spec compliant.

```
> semver.coerce('0000.004.02', { loose: true }).version
'0.4.2'
```

**Pull request closed without merging**
